package rules

import rw.wys.tms.domain.Task;
import rw.wys.tms.domain.User;

rule "Assigned Task Status Rule6"
		when
			userobject:User(username!=null)
			taskobject:Task((status=="Unassigned"||status==null||status.equals("")));
		then
			taskobject.setStatus("Assigned");
end

rule "In Progress Task Status Rule"
		when
			taskobject:Task(status=="Assigned")
		then
			taskobject.setStatus("In Progress");
end

rule "Completed Task Status Rule"
		when
			taskobject:Task(status=="In Progress")
		then
			taskobject.setStatus("Completed");
end

rule "Closed Task Status Rule"
		when
			taskobject:Task(status=="Completed")
		then
			taskobject.setStatus("Closed");
end
